#[server]
## 서버를 헤드리스 모드로 실행하여 터미널 기반 환경에서도 앱을 실행할 수 있습니다.
#headless = true  # 서버를 헤드리스 모드로 실행
## 애플리케이션이 실행될 포트를 변경합니다. 기본값은 8501이지만, 필요에 따라 다른 포트를 사용할 수 있습니다.
#port = 8501  # 기본 포트
## CORS(Cross-Origin Resource Sharing)를 활성화하거나 비활성화할 수 있습니다. 외부에서 API를 호출할 때 중요한 설정입니다.
#enableCORS = false  # CORS 비활성화 (Cross-Origin Resource Sharing)
## 앱이 실행되는 동안 파일의 변경을 감지하지 않도록 설정할 수 있습니다. 이는 성능을 높이는데 유용할 수 있습니다.
#fileWatcherType = "auto"  # 기본값은 "auto" "none"

[theme]
primaryColor = "#cde8b9"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#000000"
font = "sans serif"

[global]
# debug, info, warning, error 중 선택 가능
logLevel = "debug"  # 로깅 레벨을 디버그로 설정

[browser]
# Streamlit은 기본적으로 익명 사용 통계를 수집합니다. 이를 비활성화할 수 있습니다.
gatherUsageStats = false  # 익명 사용 통계 수집 비활성화

[runner]
# Streamlit의 "매직" 명령어를 비활성화하여 명시적인 st.write 등을 요구할 수 있습니다.
magicEnabled = false  # 매직 명령어 비활성화 (예: `st.write`를 생략 가능하게 하는 기능)

# Streamlit의 캐시 기능을 이용해, 계산 비용이 높은 함수의 결과를 저장하고 재사용할 수 있습니다. 이를 최적화하는 방법을 설정할 수 있습니다.

[cache]
persist = true  # 캐시 데이터를 디스크에 저장
maxEntries = 100  # 최대 캐시 항목 수

# 사용자가 업로드할 수 있는 파일의 최대 크기를 설정합니다.
[server]
maxUploadSize = 200  # 단위는 MB, 기본값은 200MB